### ISSUE TITLE
[1.1.2] Synced Enum types fail to compile

### ISSUE THREAD

**Issue by techanon** [vrchat-community/UdonSharp#75]
**Describe the bug in detail:**
After upgrading to 1.1.2, I am getting the following error type:
`[UdonSharp] Packages/dev.architech.protv/Runtime/Core/TVManagerData.cs(17,42): Cannot sync type 'ArchiTech.ProTV.TVPlayState'`
The TVPlayState is an enum and it compiles perfectly fine after downgrading back to 1.1.1

I think it has to do with this commit portion:
https://github.com/vrchat-community/UdonSharp/commit/884e49b180de028791220466c950122cb08f86a6#diff-9d803f448d7a5ca806190f1f1f41999d4071c8d64a2f332679514ea838a3d19cR840

**Provide steps/code to reproduce the bug:**
Create an U# behaviour with an enum as a synced variable and run the compile.

**Expected behavior:**
Compiles correctly to an int.

**Comment by MerlinVR** [comment]
Thanks! Should be fixed in b72e19f35f3f8c095d8145c2a39364b8a5caa4c9 will look at getting a release out with the fix tomorrow

**Comment by MerlinVR** [comment]
Resolved in 1.1.3 (obtainable via VCC 1.1.4 because reasons)

**Comment by Miner28** [comment]
> Resolved in 1.1.3 (obtainable via VCC U# 1.1.4 because reasons)

![image](https://user-images.githubusercontent.com/1560327/198850247-5abca298-db8f-4139-bbbc-13034c22c2da.png)
Still not fixed for arrays

**Comment by MerlinVR** [comment]
Thanks, the array fix will probably be in a release on Monday
